# Generated by Django 3.0.8 on 2020-07-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='document',
            field=models.FileField(default='Abc', upload_to='media/'),
            preserve_default=False,
        ),
    ]
